src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AddressRepository::class)
 */
class Address
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fullname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $company;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $address_details;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="addresses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;


    public function __toString()
    {
        $result = $this->fullname."[spr]";
        if($this->getCompany()){
            $result .= $this->company."[spr]";
        }
        $result .= $this->address."[spr]";
        if($this->getAddressDetails()){
            $result .= $this->address_details."[spr]";
        }       
        $result .= $this->postalCode." - ".$this->city."[spr]";
        $result .= $this->country."[spr]";
        $result .= "Phone : ".$this->phone."[spr]";

        return $result;
    
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(string $fullname): self
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(?string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getAddressDetails(): ?string
    {
        return $this->address_details;
    }

    public function setAddressDetails(?string $address_details): self
    {
        $this->address_details = $address_details;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postalCode;
    }

    public function setPostalCode(int $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/AddressType.php
<?php

namespace App\Form;

use App\Entity\Address;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddressType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('fullname')
            ->add('company')
            ->add('address')
            ->add('address_details')
            ->add('phone')
            ->add('city')
            ->add('postalCode')
            ->add('country',CountryType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Address::class,
        ]);
    }
}

src/Controller/AddressController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Form\AddressType;
use App\Services\CartServices;
use App\Repository\AddressRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/address")
 */
class AddressController extends AbstractController
{
    
    private $session;
    public function __construct(ProductRepository $productRepository, SessionInterface $session){
    $this->productRepository = $productRepository;
    $this->session = $session;
    }
    /**
     * @Route("/", name="address_index", methods={"GET"})
     */
    public function index(AddressRepository $addressRepository): Response
    {
        return $this->render('address/index.html.twig', [
            'addresses' => $addressRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="address_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, CartServices $cartServices): Response
    {
        
        $address = new Address();
        $form = $this->createForm(AddressType::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user= $this->getUser();
            $address->setUser($user);
            $entityManager->persist($address);
            $entityManager->flush();

            if($cartServices->getAllProductCart()){
                return $this->redirectToRoute('checkout');
            }
            
            $this->addFlash('address_message', 'Your address has been saved');
            return $this->redirectToRoute('account', [], Response::HTTP_SEE_OTHER);
        }

        $products = $this->productRepository->findALL();
        return $this->render('address/new.html.twig', [
            'address' => $address,
            'form' => $form->createView(),
            'products'=>$products 

        ]);
    }


    /**
     * @Route("/{id}/edit", name="address_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Address $address, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AddressType::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            if ($this->session->get('checkout_data')) {
                $data = $this->session->get('checkout_data');
                $data['address'] = $address;
                $this->session->set('checkout_data',$data);
                return $this->redirectToRoute("checkout_confirm");
                
            }
            $this->addFlash('address_message', 'Your address has been updated');
            return $this->redirectToRoute('account', [], Response::HTTP_SEE_OTHER);
        }
        $products = $this->productRepository->findALL();
        return $this->renderForm('address/edit.html.twig', [
            'address' => $address,
            'form' => $form,
            'products'=>$products 
        ]);
    }

    /**
     * @Route("/{id}", name="address_delete", methods={"POST"})
     */
    public function delete(Request $request, Address $address, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$address->getId(), $request->request->get('_token'))) {
            $entityManager->remove($address);
            $entityManager->flush();
            $this->addFlash('address_message', 'Your address has been deleted');
        }
        
        return $this->redirectToRoute('account', [], Response::HTTP_SEE_OTHER);
    }
}

templates/address/_delete_form.html.twig
<form method="post" action="{{ path('address_delete', {'id': address.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ address.id) }}">
    <button class="btn btn-border-fill btn-block">Delete</button>
</form>

templates/address/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-border-fill btn-block mt-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/address/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Address{% endblock %}

{% block body %}
{{ include("partials/title-section.html.twig", {'name':'Edit Address'}) }}
    <div class="login_register_wrap section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-6 col-md-10">
                    <div class="login_wrap">
                        <div class="padding_eight_all bg-white">
                            <div class="heading_s1">
                                <h3>Edit Address</h3>
                            </div>
                            <div class="content">
                            {{include('address/_form.html.twig', {'button_label': 'Update'})}}<br>
                            <a class="btn btn-fill-out btn-block" href="{{ path('account') }}">back to account</a>
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>  
{% endblock %}

templates/address/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Address index{% endblock %}

{% block body %}
    <h1>Address index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Fullname</th>
                <th>Company</th>
                <th>Address</th>
                <th>Address_details</th>
                <th>Phone</th>
                <th>City</th>
                <th>PostalCode</th>
                <th>Country</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for address in addresses %}
            <tr>
                <td>{{ address.id }}</td>
                <td>{{ address.fullname }}</td>
                <td>{{ address.company }}</td>
                <td>{{ address.address }}</td>
                <td>{{ address.addressDetails }}</td>
                <td>{{ address.phone }}</td>
                <td>{{ address.city }}</td>
                <td>{{ address.postalCode }}</td>
                <td>{{ address.country }}</td>
                <td>
                    <a href="{{ path('address_show', {'id': address.id}) }}"><button class="btn btn-success p-2" style="text-align:center"><i class="fas fa-eye"></i>
    
</button></a>
                    <a href="{{ path('address_edit', {'id': address.id}) }}"><button class="btn btn-info p-2" style="text-align:center"><i class="fas fa-edit"></i>
    
</button></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="mt-5 mb-5">
    <a class="btn btn-fill-out btn-block" href="{{ path('address_new') }}">Create new</a><br>
    <a class="btn btn-fill-out btn-block" href="{{ path('account') }}">Back to account</a>
    </div>
{% endblock %}

templates/address/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Address
{% endblock %}

{% block body %}
	{{ include("partials/title-section.html.twig", {'name':'Add Address'}) }}
	<div class="login_register_wrap section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-xl-6 col-md-10">
					<div class="login_wrap">
						<div class="padding_eight_all bg-white">
							<div class="heading_s1">
								<h3>Add Address</h3>
							</div>
							<div class="message-flash">
								{% for message in app.flashes('checkout_message') %}
									<div class="alert alert-success alert-dismissible fade show" role="alert">
										{{message}}
										<button type="button" class="close" data-dismiss="alert" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
								{% endfor %}

							</div>
							<div class="content">
								{{ include('address/_form.html.twig') }}
								<a class="btn btn-border-fill btn-block mt-2" href="{{ path('account') }}">Back to account</a>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


{% endblock %}

templates/address/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Address{% endblock %}

{% block body %}
    <h1>Address</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ address.id }}</td>
            </tr>
            <tr>
                <th>Fullname</th>
                <td>{{ address.fullname }}</td>
            </tr>
            <tr>
                <th>Company</th>
                <td>{{ address.company }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ address.address }}</td>
            </tr>
            <tr>
                <th>Address_details</th>
                <td>{{ address.addressDetails }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ address.phone }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ address.city }}</td>
            </tr>
            <tr>
                <th>PostalCode</th>
                <td>{{ address.postalCode }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ address.country }}</td>
            </tr>
        </tbody>
    </table>
    <div class="mt-5 mb-5">
    <a class="btn btn-fill-out btn-block" href="{{ path('address_index') }}">back to list</a><br>

    <a class="btn btn-fill-out btn-block" href="{{ path('address_edit', {'id': address.id}) }}">edit</a><br>

    {{ include('address/_delete_form.html.twig') }}
    </div>
{% endblock %}